apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongo

resources:
  - ../../base

patches:
  - path: patch-storageclass.yaml
  - path: patch-nodeSelector.yaml
  - path: patch-statefulset.yaml