apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-
nameSuffix: ""

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: grade-submission-api
  - path: service-type-patch.yaml
    target:
      kind: Service
      name: grade-submission-api
