apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-rs-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/codeicu120/argocd-kubernetes-gitops-tutorial.git   # ğŸ‘ˆ æ”¹æˆä½ çš„
    targetRevision: main                                        # æˆ–å…¶ä»–åˆ†æ”¯
    path: infra/mongodb/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true