apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/codeicu120/argocd-kubernetes-gitops-tutorial.git
    targetRevision: HEAD
    path: infra/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: default    # StorageClass 是 cluster 级，这里写哪个 namespace 无所谓
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true